export const APP_INFO = {
  APP_NAME: "Shree Siddhasankalpa Ayurvedalaya",
  APP_DESCRIPTION: "Generated by Shree Siddhasankalpa Ayurvedalaya",
  APP_ADDRESS:
    "Door No.4-7/F-8, Near Canara Bank, Shrinivasa Nagara,\nKajaraguttu, Anjar Village, Hiriadka Post, Udupi - 576113",
  APP_PHONE_NUMBER: "Ph.No. - 7411736225",
  APP_REGISTRATION_ID: "Reg.No. - 41159",
  APP_EMAIL: "shree.siddhasankalpa.ayurveda@gmail.com",
  APP_DOCTOR:"Vd. Rohit Ramesh Prabhu",
  APP_DEGREE:"BAMS, MD(Ayurveda Samhita & Siddhanta)",
  APP_SPECIALITY:"Viddhakarma & Agnikarma Specialist",
};


export const LOCATION_OPTIONS = [
  { value: "UDP", label: "Udupi" },
  { value: "MNI", label: "Mangaon" },
  { value: "OTHER", label: "Other" },
];

export const GENDER_OPTIONS = [
  { value: "Male", label: "Male" },
  { value: "Female", label: "Female" },
  { value: "Others", label: "Others" },
];
